name: Déploiement vers le cPanel WHC

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Déployer vers WHC via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: github@chairecara.uqam.ca
          server: chairecara.uqam.ca
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './www/*'
          remote_path: /home/chairecara/public_html
          sftp_only: true
 
 



